mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

birdseye:
  enabled: true
  mode: continuous

objects:
  track:
    - person

cameras:
  escalera:
    ffmpeg:
      inputs:
        - path: rtsp://Marcos:12345678@192.168.1.11:554/stream1
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      continuous:
        days: 0
      motion:
        days: 7
version: 0.17-0